[local]
localhost

[mongodb]
mongodb.arjundevops.xyz

[redis]
redis.arjundevops.xyz

[mysql]
mysql.arjundevops.xyz

[rabbitmq]
rabbitmq.arjundevops.xyz

[catalogue]
catalogue.arjundevops.xyz

[user]
user.arjundevops.xyz

[cart]
cart.arjundevops.xyz

[shipping]
shipping.arjundevops.xyz

[payment]
payment.arjundevops.xyz

[frontend]
frontend.arjundevops.xyz

[private-key-demo]
172.31.37.172